services:
  - type: web
    name: contentflow-ai
    env: node
    plan: free
    region: oregon
    rootDir: contentflow-ai
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXT_PUBLIC_APP_URL
        value: "https://contentflow-ai-ex6w.onrender.com"
      - key: GEMINI_API_KEY
        value: "AIzaSyACZ_QGAYPvQAmg0fOf18jOapy-H1DbMnI"
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: "AIzaSyBRp4j5_Yydv8U9zwoKskzGV4BUSxfINHs"
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: "contentflow-ai-juang26.firebaseapp.com"
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: "contentflow-ai-juang26"
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: "contentflow-ai-juang26.firebasestorage.app"
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "939924050941"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: "1:939924050941:web:0a595064b5ce861401bf94"
      - key: STRIPE_SECRET_KEY
        value: "sk_test_51TXh1MRelKz6KPZRjvvhzUCoKjCAFGxfNi4Dxy5hY4of9EYIl2c5SDwSQapkLI3LzbiAVRQJmLbdH3XGJbsa35NS00NV1ibjyt"
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        value: "pk_test_123"
      - key: STRIPE_WEBHOOK_SECRET
        value: "whsec_agyuFzmzl9Prx9WWCShdEPuIn9nmzwY9"
      - key: STRIPE_STARTER_PRICE_ID
        value: "price_1TYR0ZRelKz6KPZREQKLXDvt"
      - key: STRIPE_PRO_PRICE_ID
        value: "price_1TYR0oRelKz6KPZRdBETJzhZ"
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
